config/routes.rb
ConnectWithSoundCloudDemo::Application.routes.draw do
  root :to => "welcome#index"

  match '/you',           :to => 'welcome#show',    :as => :you
  match '/you/update',    :to => 'welcome#update',  :as => :you_update

  match '/soundcloud/connect',    :to => 'soundcloud#connect',    :as => :soundcloud_connect
  match '/soundcloud/connected',  :to => 'soundcloud#connected',  :as => :soundcloud_connected
  match '/soundcloud/disconnect', :to => 'soundcloud#disconnect', :as => :soundcloud_disconnect

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/user.rb
class User < ActiveRecord::Base
  SOUNDCLOUD_CLIENT_ID     = "a4e5baea6fd927f45189f90101814ed9"
  SOUNDCLOUD_CLIENT_SECRET = "0b7ffb62510fd1eda7633262ba433f56"

  def self.soundcloud_client(options={})
    options = {
      :client_id     => SOUNDCLOUD_CLIENT_ID,
      :client_secret => SOUNDCLOUD_CLIENT_SECRET,
    }.merge(options)

    Soundcloud.new(options)
  end
  
  
  def soundcloud_client(options={})
    options= {
      :expires_at    => soundcloud_expires_at,
      :access_token  => soundcloud_access_token,
      :refresh_token => soundcloud_refresh_token
    }.merge(options)
    
    client = self.class.soundcloud_client(options)
    
    # define a callback for successful token exchanges
    # this will make sure that new access_tokens are persisted once an existing 
    # access_token expired and a new one was retrieved from the soundcloud api
    client.on_exchange_token do
      self.update_attributes!({
        :soundcloud_access_token  => client.access_token,
        :soundcloud_refresh_token => client.refresh_token,
        :soundcloud_expires_at    => client.expires_at,
      })
    end
    
    client
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :login_from_session
  
  def logged_in?
    !!current_user
  end
  
  def current_user
    @current_user
  end
  
  def login_as(user)
    @current_user = user
    session[:current_user_id] = user.try(:id)
  end

  def login_from_session
    @current_user = User.find_by_id(session[:current_user_id])
  end
end

app/controllers/soundcloud_controller.rb
class SoundcloudController < ApplicationController
  def connect
    redirect_to soundcloud_client.authorize_url(:display => "popup")
  end

  def connected
    if params[:error].nil?
      soundcloud_client.exchange_token(:code => params[:code])
      me = soundcloud_client.get("/me")

      login_as User.find_or_create_by_soundcloud_user_id({
        :soundcloud_user_id  => me.id,
        :soundcloud_username => me.username
      })

      current_user.update_attributes!({
        :soundcloud_access_token  => soundcloud_client.access_token,
        :soundcloud_refresh_token => soundcloud_client.refresh_token,
        :soundcloud_expires_at    => soundcloud_client.expires_at,
      })
    end
    render :layout => false
  end

  def disconnect
    login_as nil
    redirect_to root_path
  end
  
private

  def soundcloud_client
    return @soundcloud_client if @soundcloud_client
    @soundcloud_client = User.soundcloud_client(:redirect_uri  => soundcloud_connected_url)
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def show
    @tracks = current_user.soundcloud_client.get("/me/tracks", :limit => 5)
    @me     = current_user.soundcloud_client.get("/me")
  end

  def update
    res = current_user.soundcloud_client.put("/me", :user => {:description => params[:description]})
    redirect_to :action => :show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user
  end

  def logged_in?
    !!current_user
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GrooveCrowd - Where Artists Get Together</title>
  <!--<script src="http://connect.soundcloud.com/base.js"></script>-->
  <%= stylesheet_link_tag 'http://soundcloudfront.com/stylesheets/style.css', 'application', 'soundcloud' %>
  <%= stylesheet_link_tag 'style.css'%>
  <%= stylesheet_link_tag 'bootstrap.css', 'application'%>
  <%= stylesheet_link_tag 'bootstrap-responsive.css', 'application'%>
  <%= javascript_include_tag 'jquery-1.5.min', 'connect', 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#">Groove Crowd</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#">Artists</a></li>
              <li><a href="#">News</a></li>
            </ul>
            <!--<form class="navbar-form pull-right">
              <input class="span2" type="text" placeholder="Email">
              <input class="span2" type="password" placeholder="Password">
              <button type="submit" class="btn">Sign in</button>
            </form>-->
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <%= yield %>
    <footer>
    	<div class="container">
          <p style="font-size:12px">&copy; GrooveCrowd 2013 - All Rights Reserved</p>
        </div>
    </footer>
</body>
</html>

app/views/soundcloud/connected.html.erb
<!DOCTYPE html>
<html lang="en">
  <head><meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>GrooveCrowd - Where Artists Get Together</title>
  </head>
  <body onload="window.opener.SC.Connect.popupCallback(window)">
    <b style="width: 100%; text-align: center;">This popup should automatically close in a few seconds<b>
  </body>
</html>

app/views/welcome/index.html.erb
<style>
  	body {
		background: url('images/bg.jpg') #fff;
  		background-size: 1440px 800px;
  		background-repeat:no-repeat;
	}
  </style>
<div class="container" style="min-height:550px" align="center">
<div class="lead">
        <div class="lead pull-right" style="margin:80px 30px 0 0; background-color:#333; opacity: 0.8; padding:15px 25px; color:#fff;">
        	<h1>Create Your Artist Profile</h1>
            <hr>
            <h2>Include your Soundcloud songs</h2>
            <hr>
            <h3>Your Instagram photos</h3>
            <hr>
            <h4>YouTube videos, upcoming concerts and more</h4>
            <div style="padding:15px 0;" class="connect-with-soundcloud <%= "connected" if logged_in? %>">
                <%= link_to "Connect With SoundCloud",    soundcloud_connect_path, :class => "connect" %>
                <%= link_to "Disconnect From SoundCloud", soundcloud_disconnect_path, :class => "disconnect" %>
                <span class="current-user">
                    You are logged in as:
                    <span class="username"><%= current_user.soundcloud_username if logged_in? %></span>
                </span>
            </div>
            <div class="visible-when-logged-in <%= "hidden" unless logged_in? %>"">
                <%= link_to "Check out your profile", you_path %>
            </div>
        </div>
</div>

</div> <!-- /container -->

app/views/welcome/show.html.erb
<div class="container" style="margin-top:10px;">
    	<div class="row-fluid">
            <div class="pull-left" style="width:228px;">
                <%= image_tag(@me.avatar_url, :class => "img-polaroid", :size => "210x210") %>
            </div>
            <div class="social-icons pull-left" style="width:940px;">
            	<ul class="pull-right">
                    <a href="#"><%= image_tag("facebook.png", :alt => "Facebook", :size => "28x28") %></a>
                    <a href="#"><%= image_tag("twitter.png", :alt => "Twitter", :size => "28x28") %></a>
                    <a href="#"><%= image_tag("googleplus.png", :alt => "Google Plus", :size => "28x28") %></a>
                </ul>
                <h2 style="line-height:25px;"><%= @me.username %> <br/>
                    <small style="padding-left:2px; font-size:14px">Alternative Rock <span>- <%= @me.city %>, <%= @me.country %></span></small>
                </h2>
                <iframe src="http://widget.stagram.com/in/maria_melodia/?s=120&w=7&h=1&b=1&p=5" allowtransparency="true" frameborder="0" scrolling="no" style="border:none;overflow:hidden;width:940px; height: 135px; margin-top:10px;"></iframe>
            </div>
        </div>
    	<div class="row-fluid"  style="margin-top:10px;">
        	<div class="span7">
            	<div style="background-color:#444;padding:10px 15px; color:#fff;"><h4 style="font-weight: 200;">Recent updates</h4></div>
            	<div class="thumbnail-text">
                	<div class="form-inline" align="center">
                        <form>
                            <input type="text" class=" input-xxlarge" placeholder="Share something with your fans">
                            <button type="submit" class="btn">Share</button>
                            <div align="left"><small style="padding:5px 0 0 20px;"><a href="#">attach picture</a></small></div>
                        </form>
                    </div>
                    <hr>
                  <span>É o que testemunhamos neste concerto gravado no chão do Marco Zero, na ilha holandesa do Recife Velho ou Antigo, porta e farol da cidade para o mundo. Ouviram não só do Ipiranga, ouviram d´África, onde os tambores da Nação fazem reverberar o escambo de oferendas no terreiro afro-beat. 
  
  Mais do que um show, o DVD mostra a liga orgânica entre a cidade e a banda. Rios, pontes, overdrives e impressionantes coreografias da massa vistas por câmeras aéreas. Os “extras” completam essa lição geográfica da fome afetiva com um rolê por alguns pontos como o Mercado de São José e o bairro de Peixinhos, Olinda, de onde veio a “cozinha” percussiva do grupo. 
  
  No repertório, clássicos dos tempos de Chico Science são mesclados com a história da NZ até hoje. Fred 04, parceiro da origem do mangue beat; Siba com a loa-metal da sua Fuloresta; Arnaldo Antunes e Paralamas do Sucesso fazem participações especiais. 
  
  Este DVD é um documento digno daquela que é, desde o nascedouro, nos anos 90, a melhor e mais expressiva banda brasileira. Não é fácil se manter com essa garantia e resistência do grupo formado por Jorge Du Peixe, Pupillo, Lúcio Maia, Dengue, Toca Ogan, Gilmar Bola 8, Da Lua e Marcos Matia. - See more at: http://www.nacaozumbi.com.br/#sthash.ZkyUYww6.dpuf</span>
                  <hr>
                  <span>
                  	<h3>verdade é igual mertiolate arde mas acaba funcionando como remédio também.Primeiro vem o ardor do instante, depois vem a cura pro machucado</h3>
                    <img alt="Tumblr_mdx29xahmi1r8rt3po1_500_large" src="http://data.whicdn.com/images/44089346/tumblr_mdx29xAHmI1r8rt3po1_500_large.jpg">
                  </span>
                  <hr>
                  <span><img src="http://25.media.tumblr.com/2fdac407b479dc6a4badeb17e69737ea/tumblr_mfe2adlMab1rjazmfo1_400.jpg"></span>
                  <hr>
				</div>
        	</div>
        	
        	<div class="span5" style="border-top:#ccc solid 5px;">
            	<div style=" padding:10px 15px; background-color:#f2f2f4; text-transform:uppercase; margin-top:10px;"><b>Upcoming Concerts</b></div>
                <table class="table table-condensed" style="font-size:12px; border-bottom:#ccc solid 5px;max-height:300px !important; overflow:auto;">
                	<thead>
                    	<tr>
                        	<th>Date</th>
                            <th>Local</th>
                            <th>City</th>
                            <th>Tickets</th>
                        </tr>
                    </thead>
                    <tbody style="">
                    	<tr>
                        	<td>01-ago-13</td>
                            <td>Music Hall</td>
                            <td>Belo Horizonte, Brasil</td>
                            <td><a href="#" target="_blank" class="btn btn-mini btn-danger">Buy tickets</a></td>
                        </tr>
                        <tr>
                        	<td>01-ago-13</td>
                            <td>Music Hall</td>
                            <td>Belo Horizonte, Brasil</td>
                            <td><a href="#" target="_blank" class="btn btn-mini btn-danger">Buy tickets</a></td>
                        </tr>
                        <tr>
                        	<td>01-ago-13</td>
                            <td>Music Hall</td>
                            <td>Belo Horizonte, Brasil</td>
                            <td><a href="#" target="_blank" class="btn btn-mini btn-danger">Buy tickets</a></td>
                        </tr>
                        <tr>
                        	<td>01-ago-13</td>
                            <td>Music Hall</td>
                            <td>Belo Horizonte, Brasil</td>
                            <td><a href="#" target="_blank" class="btn btn-mini btn-danger">Buy tickets</a></td>
                        </tr>
                        <tr>
                        	<td>01-ago-13</td>
                            <td>Music Hall</td>
                            <td>Belo Horizonte, Brasil</td>
                            <td><a href="#" target="_blank" class="btn btn-mini btn-danger">Buy tickets</a></td>
                        </tr>
                        <tr>
                        	<td>01-ago-13</td>
                            <td>Music Hall</td>
                            <td>Belo Horizonte, Brasil</td>
                            <td><a href="#" target="_blank" class="btn btn-mini btn-danger">Buy tickets</a></td>
                        </tr>
                        <tr>
                        	<td>01-ago-13</td>
                            <td>Music Hall</td>
                            <td>Belo Horizonte, Brasil</td>
                            <td><a href="#" target="_blank" class="btn btn-mini btn-danger">Buy tickets</a></td>
                        </tr>
                        <tr>
                        	<td>01-ago-13</td>
                            <td>Music Hall</td>
                            <td>Belo Horizonte, Brasil</td>
                            <td><a href="#" target="_blank" class="btn btn-mini btn-danger">Buy tickets</a></td>
                        </tr>
                    </tbody>
                </table>
                <iframe style="width:100%" height="285" src="http://www.youtube.com/embed/wIgrPf1TCXc" frameborder="0" allowfullscreen></iframe>
                <iframe style="width:100%" height="285" src="http://www.youtube.com/embed/cIdhtP6018g" frameborder="0" allowfullscreen></iframe>
                <iframe style="width:100%" height="285" src="http://www.youtube.com/embed/ivDizTT0aBg" frameborder="0" allowfullscreen></iframe>
                <div id="fb-root"></div>
                <div style="padding-top:10px;" class="fb-comments" data-href="http://jobconvo.com" data-width="470" data-num-posts="10"></div>
        	</div>
        </div>
    </div> <!-- /container -->
    <hr>
    <%= javascript_include_tag 'instafeed.min.js' %>
    <%= javascript_include_tag 'http://stratus.sc/stratus.js' %>
    <script type="text/javascript">
	  $(document).ready(function(){
		$.stratus({
			auto_play: false,
			links: 'https://soundcloud.com/maria-melodia/sets/debut',
			random: true,
			download: true,
		});
	  });
	</script>
	<script type="text/javascript">
		(function(d, s, id) {
		  var js, fjs = d.getElementsByTagName(s)[0];
		  if (d.getElementById(id)) return;
		  js = d.createElement(s); js.id = id;
		  js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1&appId=450859074991785";
		  fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));
    </script>